[package]
name = "rust-web-boilerplate"
version = "0.1.0"
authors = ["Sven-Hendrik Haase <svenstaro@gmail.com>"]

[lib]
name = "rust_web_boilerplate"
path = "src/lib.rs"

[[bin]]
name = "rust_web_boilerplate_runner"
path = "src/main.rs"

[[test]]
name = "tests"
path = "tests/lib.rs"

[dependencies]
uuid = { version = "0.5", features = ["use_std", "serde", "v4"] }
chrono = { version = "0.4", features = ["serde"] }
argon2rs = "0.2"
rocket = { git = "https://github.com/SergioBenitez/Rocket.git" }
rocket_codegen = { git = "https://github.com/SergioBenitez/Rocket.git" }
# rocket = { version = "0.3", features = ["testing"] }
# rocket_codegen = "0.3"
diesel = { git = "https://github.com/diesel-rs/diesel.git", features = ["postgres", "uuid", "chrono", "serde_json"] }
diesel_codegen = { git = "https://github.com/diesel-rs/diesel.git", features = ["postgres"] }
r2d2 = "0.7"
r2d2-diesel = "0.13"
# dotenv = "0.8.0" TODO Make use of this later.
serde = "1"
serde_json = "1"
serde_derive = "1"
validator = "0.4"
validator_derive = "0.5"
ring = "0.11"

[replace]
"diesel:0.13.0" = { git = "https://github.com/diesel-rs/diesel.git" }

[dev-dependencies]
quickcheck = "0.4"
stainless = "0.1"
parking_lot = {version = "0.4", features = ["nightly"]}

[dependencies.rocket_contrib]
# version = "0.3"
git = "https://github.com/SergioBenitez/Rocket.git"
default-features = false
features = ["json"]
